studmanage/studmanage/urls.py
from django.contrib import admin
from django.urls import path, re_path

from smapp.views import (
    SchoolView,
    SchoolClassView,
    StudentView,
    Grades,
    StudentSearchView,
    AddStudentView,
    PresenceListView,
    SchoolSubjectCreateView,
    MessageFormView,
    UserListView,
    LoginView,
    LogoutView,
    ChangePassView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', SchoolView.as_view(),
         name="index"),
    path('class/<int:school_class>', SchoolClassView.as_view(),
         name="school-class"),
    re_path(r'^student/(?P<student_id>(\d)+)', StudentView.as_view(),
            name="student_details"),
    re_path(r'^grades/(?P<student_id>(\d)+)/(?P<subject_id>(\d)+)', Grades.as_view(),
            name="student_grades"),
    re_path(r'^student_search', StudentSearchView.as_view(),
            name="student_search"),
    re_path(r'^add_student', AddStudentView.as_view(),
            name="add_student"),
    re_path(r'^class_presence/(?P<student_id>(\d)+)/(?P<date>\d{4}-\d{2}-\d{2})$', PresenceListView.as_view(),
            name="class_presence"),
    re_path(r'create_school_subject', SchoolSubjectCreateView.as_view(),
            name="create_school_subject"),
    re_path(r'compose_message', MessageFormView.as_view(),
            name="compose_message"),
    re_path(r'list_users', UserListView.as_view(),
            name="list_users"),
    re_path(r'login', LoginView.as_view(),
            name="login"),
    re_path(r'logout', LogoutView.as_view(),
            name="logout"),
    re_path(r'reset_password/(?P<user_id>(\d)+)$', ChangePassView.as_view(),
            name="reset_password"),
]

studmanage/smapp/models.py
from django.db import models

# Create your models here.

SCHOOL_CLASS = (
    (1, "1a"),
    (2, "1b"),
    (3, "2a"),
    (4, "2b"),
    (5, "3a"),
    (6, "3b"),
)

GRADES = (
    (1, "1"),
    (1.5, "1+"),
    (1.75, "2-"),
    (2, "2"),
    (2.5, "2+"),
    (2.75, "3-"),
    (3, "3"),
    (3.5, "3+"),
    (3.75, "4-"),
    (4, "4"),
    (4.5, "4+"),
    (4.75, "5-"),
    (5, "5"),
    (5.5, "5+"),
    (5.75, "6-"),
    (6, "6")
)


class SchoolSubject(models.Model):
    name = models.CharField(max_length=64)
    teacher_name = models.CharField(max_length=64)

    @property
    def name2(self):
        return "{} - {}".format(self.teacher_name, self.name)

    def __str__(self):
        return self.name2


class Student(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    school_class = models.IntegerField(choices=SCHOOL_CLASS, verbose_name='Klasa')
    grades = models.ManyToManyField(SchoolSubject, through="StudentGrades")
    year_of_birth = models.IntegerField(null=True, blank=True, verbose_name='Rok urodzenia')  # blank pozwala na wyslanie niewypenionego pola
    suspended = models.BooleanField(default=False, verbose_name='Zawieszony')

    @property
    def name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.name


class StudentGrades(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)
    grade = models.FloatField(choices=GRADES)


class PresenceList(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    day = models.DateField()
    present = models.NullBooleanField()


class Message(models.Model):
    subject = models.CharField(max_length=256, verbose_name='Temat')
    content = models.TextField(null=True)
    date_sent = models.DateTimeField(auto_now_add=True)  # tylko data utworzenia, auto_now - czas ostatniego uzycia
    to = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)
    author = models.ForeignKey(Student, on_delete=models.CASCADE)

studmanage/smapp/forms.py
from django import forms

from .validators import range_validator
from .models import (
    SCHOOL_CLASS, Student, SchoolSubject, Message
)


class StudentSearchForm(forms.Form):

    name = forms.CharField(label='Nazwisko ucznia')


class AddStudentForm(forms.Form):

    first_name = forms.CharField(label='Imie', max_length=64)
    last_name = forms.CharField(label='Nazwisko', max_length=64)
    school_class = forms.ChoiceField(label='Klasa', choices=SCHOOL_CLASS)
    year_of_birth = forms.IntegerField(label="Data urodzenia", validators=[range_validator])


class PresenceListForm(forms.Form):

    student = forms.ModelChoiceField(label='Student', queryset=Student.objects.all())
    day = forms.DateField(label='Data', widget=forms.HiddenInput())
    present = forms.NullBooleanField(label='Obecnosc')


class SchoolSubjectForm(forms.ModelForm):
    class Meta:
        model = SchoolSubject
        # fields = '__all__'
        fields = ['name', 'teacher_name']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['date_sent']


class LoginForm(forms.Form):
    login = forms.CharField(label='Login')
    password = forms.CharField(label='Haslo', widget=forms.PasswordInput)


class ChangePassForm(forms.Form):
    old_pass = forms.CharField(widget=forms.PasswordInput())
    new_pass = forms.CharField(widget=forms.PasswordInput())
    new_pass_2 = forms.CharField(widget=forms.PasswordInput())

studmanage/smapp/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse, reverse_lazy

# Create your views here.
from .models import (
    SCHOOL_CLASS,
    Student,
    SchoolSubject,
    StudentGrades,
    PresenceList,
)

from .forms import (
    StudentSearchForm,
    AddStudentForm,
    PresenceListForm,
    SchoolSubjectForm,
    MessageForm,
    LoginForm,
    ChangePassForm,
)


class SchoolView(View):

    def get(self, request):
        ctx = {
            'classes': SCHOOL_CLASS
        }
        return TemplateResponse(request, 'school_view.html', ctx)


class SchoolClassView(View):

    def get(self, request, school_class):
        students = Student.objects.filter(school_class=school_class)
        return render(request, "class.html", {"students": students,
                                              "class_name": SCHOOL_CLASS[int(school_class) - 1][1]
                                              })


class StudentView(View):

    def get(self, request, student_id):
        student = Student.objects.get(pk=student_id)
        subjects = SchoolSubject.objects.all()
        ctx = {
            "student": student,
            "subjects": subjects
        }
        return render(request, "student.html", ctx)


class Grades(View):

    def get(self, request, student_id, subject_id):
        student = Student.objects.get(pk=student_id)
        subject = SchoolSubject.objects.get(pk=subject_id)
        grades = StudentGrades.objects.filter(
            student_id=student_id,
            school_subject=subject_id
        )

        try:
            sum = 0
            for g in grades:
                sum += int(g.grade)
            avg = round(sum / len(grades), 2)
        except ZeroDivisionError:
            avg = 0

        ctx = {
            'student': student,
            'subject': subject,
            'grades': grades,
            'avg': avg,
        }
        return render(request, 'grades.html', ctx)


class StudentSearchView(View):

    def get(self, request):
        form = StudentSearchForm()
        return render(request, 'student_search.html', {'form': form})

    def post(self, request):
        form = StudentSearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            students = Student.objects.filter(last_name__icontains=name)
            # niezwaza na wielkosc znakow
            return render(request, 'student_search.html', {'form': form, 'students': students})


class AddStudentView(View):

    def get(self, request):
        form = AddStudentForm()
        return render(request, 'add_student.html', {'form': form})

    def post(self, request):
        form = AddStudentForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            school_class = form.cleaned_data['school_class']
            year_of_birth = form.cleaned_data['year_of_birth']
            new_student = Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                school_class=school_class,
                year_of_birth=year_of_birth
            )
            # new_student = Student.objects.create(**form.cleaned_data) rozpakowanie slownika
            url = reverse('student_details', kwargs={'student_id': new_student.id})   # generuje url
            return HttpResponseRedirect(url)

        else:
            return render(request, 'add_student.html', {'form': form})


class PresenceListView(View):

    def get(self, request, student_id, date):
        form = PresenceListForm(initial={'day': date})
        return render(request, 'class_presence.html', {'form': form})

    def post(self, request, student_id, date):
        form = PresenceListForm(request.POST)
        if form.is_valid():
            student = form.cleaned_data['student']
            day = form.cleaned_data['day']
            present = form.cleaned_data['present']
            PresenceList.objects.create(
                student=student,
                day=day,
                present=present
            )
            url = reverse('student_details', kwargs={'student_id': student.id})
            return HttpResponseRedirect(url)


class SchoolSubjectCreateView(CreateView):
    form_class = SchoolSubjectForm
    template_name = 'school_subject_form.html'
    success_url = reverse_lazy('create_school_subject')


class MessageFormView(CreateView):
    form_class = MessageForm
    template_name = 'message_create_form.html'
    success_url = reverse_lazy('compose_message')


class UserListView(ListView):
    model = User
    template_name = 'user_list.html'


class LoginView(View):

    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            login2 = form.cleaned_data['login']
            password = form.cleaned_data['password']
            user = authenticate(
                username=login2,
                password=password
            )
            if user is not None:
                login(request, user)
                return HttpResponse('Zalogowany {}'.format(user.username))
            else:
                return HttpResponse('Niepoprawne dane do logowania')


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))


class ChangePassView(PermissionRequiredMixin, View):
    permission_required = 'change_user'

    def get(self, request, user_id):
        form = ChangePassForm()
        return render(request, 'change_pass.html', {'form': form})

    def post(self, request, user_id):
        form = ChangePassForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=user_id)
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['old_pass']
            )
            if not user.check_password(form.cleaned_data['old_pass']):
                return HttpResponse('Niepoprane aktualne haslo')

            if form.cleaned_data['new_pass'] != form.cleaned_data['new_pass_2']:
                return HttpResponse('Nowe hasla nie s takie same')

            user.set_password(form.cleaned_data['new_pass'])
            user.save()
            return HttpResponse('Haso zmienione')

studmanage/smapp/templates/add_student.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
<h2>Nowy student:</h2>
<p>{{ new.first_name }}</p>
<p>{{ new.last_name }}</p>
<p>{{ new.get_school_class_display }}</p>

{% endblock %}

studmanage/smapp/templates/base.html
<!doctype html>
<html>

    <head>
        <meta charset="utf-8">
    </head>

    <body>
        <h1>The Beast School</h1>

        <section style="font-size: 14px">
            <hr>
            <h4 style="color:green">dev-panel</h2>
            <ul>
                <li><a href="/admin/">Admin</a></li>
                <li><a href="/student_search">Search</a></li>
                <li><a href="/add_student">Add Student</a></li>
                <li><a href="/create_school_subject">Create School Subject</a></li>
                <li><a href="/compose_message">Compose Message</a></li>
                <li><a href="/list_users">List Users</a></li>
                <li><a href="/login'">Login</a></li>
                <li><a href="/logout">Logout</a></li>
                <li><a href="/class/1">Class class-1a</a></li>
                <li><a href="/student/1">Student stud-1</a></li>
                <li><a href="/grades/1/1">Grades stud-1 sub-1</a></li>
                <li><a href="/class_presence/1/2018-03-01">Class Presence stud-1 date-2018-03-01</a></li>
                <li><a href="/reset_password/1">Reset Password stud-1</a></li>
            </ul>
            <hr>
        </section>

        <ul>
            {% block content %} {% endblock %}
        </ul>
        <footer>
            <p>{{ request.user.username }}</p>
            {% if request.user.is_authenticated %}
                <p><a href="{% url 'logout' %}">Logout</a></p>
            {% else %}
                <p><a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <p>Data: {{ date }}</p>
            <p>Data: {{ version }}</p>
        </footer>
    </body>

</html>

<!--celery, huey , task huey-->

studmanage/smapp/templates/change_pass.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock %}

studmanage/smapp/templates/class.html
{% extends 'base.html' %}

{% block content %}
    <h2>Klasa: {{ class_name }}</h2>
    <ul>
        {% for student in students %}
            <li><a href='/student/{{ student.id }}'>{{ student }}</a></li>
        {% endfor%}
    </ul>


{% endblock %}

studmanage/smapp/templates/class_presence.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">

        {% csrf_token %}
        {{ form }}

        <input type="submit">
    </form>

{% endblock %}

studmanage/smapp/templates/grades.html
{% extends 'base.html' %}

{% block content %}

    <ul>
        <li>{{ student.last_name }}</li>
        <li>{{ student.get_school_class_display }}</li>
        <li>{{ subject.name }}</li>
        <li>{{ subject.teacher_name }}</li>
        <li>{{ avg }}</li>

        {% if grades|length > 0 %}
            <li>
                <ul>
                    {% for grade in grades %}
                        <li>{{ grade.get_grade_display }}</li>
                    {% endfor %}
                </ul>
            </li>
            {% else %}
            <li>Brak ocen !</li>
        {% endif %}




{% endblock %}

studmanage/smapp/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">

        {% csrf_token %}
        {{ form }}

        <input type="submit">
    </form>

{% endblock %}

studmanage/smapp/templates/message_create_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

studmanage/smapp/templates/school_subject_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

studmanage/smapp/templates/school_view.html
{% extends 'base.html' %}

{% block content %}

    {#to jest blok#}
    {% for cls in classes %}
        <li>
            <a href='/class/{{ cls.0}}'>{{ cls.1 }}</a>
        </li>
    {%endfor %}

{% endblock %}

studmanage/smapp/templates/student.html
{% extends 'base.html' %}

{% block content %}

    <ul>
        <li>{{student.first_name }}</li>
        <li>{{student.last_name }}</li>
        <li>{{student.get_school_class_display }}</li>
    </ul>
<ul>
    {% for subject in subjects %}
        <a href='/grades/{{ student.id }}/{{subject.id}}'>{{ subject.name }}</a><br>
    {%endfor%}
</ul>


{% endblock %}

studmanage/smapp/templates/student_search.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        <select>
        {% csrf_token %}
        {{ form }}
        </select>
        <input type="submit">
    </form>
    <ul>
        {% for s in students %}
            <li>{{ s.last_name }}</li>
        {% empty %}
            <p>Studenta nie ma na lisci</p>
        {% endfor%}
    </ul>
{% endblock %}

studmanage/smapp/templates/user_list.html
<ul>
    {% for object in object_list %}
        <li>{{ object.username }}, {{ object.last_name }}</li>
    {% endfor %}
</ul>